# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distibution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"

    firebase_app_distribution(
        app: "1:518238311421:android:5d0d1165f7528ad1ae7f94",
        firebase_cli_token:"1//09eocEZOQJ5PHCgYIARAAGAkSNwF-L9IreFxNyMwz0BSIh9wPKWW32S2rsSV1qcaKyR2q2nrwxPKvLC5PJ1Rdp8tUgygZndPFQho",
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "abdelhakbouzerba019@gmail.com",
        release_notes: "New release of the app"
  )
  end
end
